### ISSUE TITLE
Remaining TODO for initial release

### ISSUE THREAD

**Issue by exaskye** [elytra/GlassHearts#1]
* [x] Lifeforce Consumed statistic
* [x] Verify automation is possible using just vanilla
* [x] Verify automation is possible with Teckle and Embers
* [x] Save attuned hearts on logout and dimension change (respawning should de-attune)
* [x] Implement Petrified Tree generator
* [x] Implement EntityAICreeperSeekHeart
* [x] Fix damage wobble spam when natural health isn't full and there are hearts refilling (what even causes this?)
* [x] Make liquid lifeforce on the ground damage undead (maybe)
* [x] Add Agate (brown gem, gives Strength when heart depleted)

**Comment by exaskye** [comment]
🎉 🎉 🎉 🎉 
🎊 🎊 🎊 🎊
